### ISSUE TITLE
How to run this app ?

### ISSUE THREAD

**Issue by itskrsna** [acailly/botpress-botfmk#1]

**Comment by acailly** [comment]
This is a plugin, the full app is here : https://botpress.io/

**Comment by itskrsna** [comment]
Can we integrate botpress with botframework @acailly

**Comment by acailly** [comment]
That's what this plugin was for, however it's not maintained anymore and I don't know how botpress evolved since. Maybe you could ask the botpress team?

**Comment by itskrsna** [comment]
I already did , but can you tell me how to integrate it to the bot ?

**Comment by itskrsna** [comment]
Or to put it in different way , is like adding this modules in bot , bye creting modules folder and in it adding a new folder call botfm , and using `npm install` , adding this module to the package.json.

**Comment by acailly** [comment]
As said in the README you had to type botpress install botfmk. If it does not work anymore it could mean that botpress has evolved in a way that is not compatible with this plugin anymore. As I said, I don't maintain this plugin anymore.

**Comment by itskrsna** [comment]
Ok thank you
